version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: pace_corridas_db
    environment:
      POSTGRES_USER: pace
      POSTGRES_PASSWORD: pace123
      POSTGRES_DB: pace_corridas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
